pushed again

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -26,17 +26,18 @@
               ARG3=$(echo $Line | cut -d: -f3); \
               ARG4=$(echo $Line | cut -d: -f4); \
               if [[ $ARG1 != *Makefile* ]]; then \
-              echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
+                echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
               fi \
               done < coding-style-reports.log
               if [ -s coding-style-reports.log ]; then
-              exit 1
+                exit 1
               fi
 
     check_program_compilation:
       runs-on: ubuntu-latest
       container:
         image: epitechcontent/epitest-docker:latest
+      depends-on: checking_coding_style
       steps:
         - name: Checkout
           uses: actions/checkout@v4 #vérif version
@@ -58,6 +59,7 @@
 
     push_to_mirror:
         runs-on: ubuntu-latest
+        depends-on: checking_coding_style
         #if: github.event_name == 'push'
         steps:
         - uses: actions/checkout@v4 #again version a vérifier
