push

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -18,12 +18,20 @@
           uses: actions/checkout@v4 #vérif version
         - name: Coding Style checker
           run: | #voir si possible de réduire c moche
-            while IFS=':' read -r ARG1 ARG2 ARG3 ARG4 _; do
-            echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"
-            done
-            if [[ -s coding-style-reports.log ]]; then
-            exit 1
-            fi
+              check.sh $(pwd) $(pwd)
+              while read Line; \
+              do \
+              ARG1=$(echo $Line | cut -d: -f1); \
+              ARG2=$(echo $Line | cut -d: -f2); \
+              ARG3=$(echo $Line | cut -d: -f3); \
+              ARG4=$(echo $Line | cut -d: -f4); \
+              if [[ $ARG1 != *Makefile* ]]; then \
+              echo "::error file=$ARG1, line=$ARG2:: $ARG3 $ARG4"; \
+              fi \
+              done < coding-style-reports.log
+              if [ -s coding-style-reports.log ]; then
+              exit 1
+              fi
 
     check_program_compilation:
       runs-on: ubuntu-latest
