plz just work

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -3,14 +3,14 @@
   on :
     push:
       branches-ignore:
-        - "ga-ignore- *" #on ignore et on force push si la commande est présente
+        - "ga-ignore- *"
 
   env:
-    EXECUTABLES: #a vérifier mais il y a un monde ou je dois mettre un truc la et c'est ce qui fout la merde
+    EXECUTABLES:
 
   jobs:
     checking_coding_style:
-      runs-on: ubuntu-latest #a voir si je peut tester sur une distro arch pour avoir un truc accurate
+      runs-on: ubuntu-latest
       container:
         image: ghcr.io/epitech/coding-style-checker:latest
       steps:
@@ -18,11 +18,11 @@
           uses: actions/checkout@v4
         - name: Coding Style checker
           run: |
-              check.sh $(pwd) $(pwd) && awk -F: '$1 !~ /Makefile/ {print "::error file="$1", line="$2":: "$3" "$4}' coding-style-reports.log
-                if [ -s $input ]; then
-                  exit 1
-              fi
-            
+            input=$(pwd)/coding-style-reports.log
+            awk -F':' '{print "::error title="$3" coding style error,file="$1",line="$2"::"$4}' $input
+            if [ -s $input ]; then
+              exit 1
+            fi
 
     check_program_compilation:
       runs-on: ubuntu-latest
@@ -45,9 +45,7 @@
                 exit 1
               fi
             done
-
     #check unit test
-
     push_to_mirror:
         runs-on: ubuntu-latest
         needs: check_program_compilation
@@ -61,8 +59,6 @@
             ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }} #clef ssh pour le repo epitech
 
             # TODO :
-            # Verifier au follow up le pourquoi du comment le miror ne se fait pas
             # voir si autre probléme
             # Voir avec Marin pour faire un truc pour les forbiden functions
             # Voir aussi pour les test unitaires, il serait temps d'en faire
-            # Avoir commande pour si test dans branche pouvoir pull request/merge la branche si tout ok ?
